{% set version = "0.6.0" %}

package:
  name: arcas-hla
  version: {{ version }}

source:
  url: https://github.com/RabadanLab/arcasHLA/archive/v{{ version }}.tar.gz
  sha256: 75bef1a5596a9dfabccb901420f5d852d6d8a15d9c676e4c94787b8d25dd708b

build:
  number: 0
  noarch: generic
  run_exports:
    - {{ pin_subpackage("arcas-hla", max_pin="x.x") }}

requirements:
  run:
    - bioconda::bedtools ==2.31.1
    - conda-forge::biopython ==1.83
    - conda-forge::coreutils ==9.4
    - conda-forge::git ==2.43.0
    - conda-forge::git-lfs ==3.4.1
    - bioconda::kallisto ==0.44.0
    - conda-forge::numpy ==1.26.4
    - conda-forge::pandas ==2.2.0
    - conda-forge::pigz ==2.8
    - conda-forge::pip ==24.0
    - conda-forge::pyarrow ==15.0.0
    - conda-forge::pytest ==8.0.0
    - conda-forge::python ==3.10.0
    - bioconda::samtools ==1.19.2
    - conda-forge::scipy ==1.12.0

test:
  commands:
    - arcasHLA --help

about:
  home: https://github.com/RabadanLab/arcasHLA
  license: GPL-3.0
  license_file: LICENSE
  summary: high resolution HLA typing from RNA seq
  description: |
    arcasHLA performs high resolution genotyping for HLA class I and class II
    genes from RNA sequencing, supporting both paired and single-end samples.

extra:
  identifiers:
    - doi:10.1093/bioinformatics/btz474
